### ISSUE TITLE
Add the initialise step on analyser

### ISSUE THREAD

**Issue by mvpmanish** [mvpmanish/Electron-Energy-Analyser-Arduino#5]
- Initialise the DACs to zero voltage on start up of the arduino

**Comment by MatthewAHarvey** [comment]
Fixed.

**Comment by MatthewAHarvey** [comment]
Forgot to save commit with #5. If you wish to see this commit, it was:
2ac5ac4e9e58bae5966e57197f0cd82d42c9f052
